# inspired by https://github.com/mrueg/repoman-travis
# inspired by https://github.com/rindeal/rindeal-ebuild-repo

dist: bionic

language: python

python:
  - pypy3

git:
  depth: 1
  quiet: true

env:
  global:
    - secure: as/AwjrTltq8gubJrcuZM8brtg2Dy/qVaNFETvenjIfHVGEwdGbvTvbdrvtD1qBr3adHI4Qd2TcBOfanTE6EW2gGq6wsLlUSCT8H69kpU4aG1vgX8D8h2zJr0ZaG8dYZOLm2isaLy7FzbdsfzgqrYshQLECdgcJod7wM43xLGqlO1sQxi0FehHVaFSCu1FW7TFAnpDM3rlk9G8kU23B1rYD+1/p0KnmQ/qIyXeCDQfHlRfPeA6Ly57ABeJWHMECeL/Jcxhj9eOEWyXObW9XgWqBIpzxFKVSWy+mJD4KoAB3MyD2mBosCYn65j6Q+NWZZoNl/HKnheekGNzXl/gAIeLaYhEzfF87K1E8JZb645XGNsl7jf55zyDlX0r4NM1fyCxRdZ02oM2t74upqqNHMdQNHoEM7UTJk7kYx+M6UWYX6RFcb9ICjRAYX8jg4ptjfiFOTH9XBTcKWopkBf9tBhIaP4e63qY+Nsx6vyZkEen09rxViT+rgZ3X97AtFPslhsJm+8Bto9w9fsToL4Zpm691GdQPe5rjtBD+feSxSIBvRKJZEoRsL84UZKeE9Nd+8PIbAuN9IDJsFDvRcZLFvZBtiAzh2NPGofIXOBYC7RvKwsFH5mFMBXNAJCNwKvDP0giOt4qtvFLnrBRDa1siXDAmTSe1WqWxh+XM8IhH0q8w=
    - PORTAGE_ROOT="$(mktemp --directory)"
    - PORTAGE_VERSION="$(tools/get_latest_portage_version)"

install:
  - tools/install_portage
  - tools/setup_portage
  - tools/add_required_user_and_group
  - export PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"

before_script:
  - pip install PyYAML
#  - pip install lxml # Not needed apparently, but stated otherwise in ebuild of portage/repoman

script:
  - repoman full --include-dev

after_success:
  - bash <(curl --silent https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

notifications:
  email:
    on_failure: change
