# inspired by https://github.com/mrueg/repoman-travis
# inspired by https://github.com/rindeal/rindeal-ebuild-repo

dist: bionic

language: python

python:
  - pypy3

git:
  depth: 1

env:
  global:
    - secure: as/AwjrTltq8gubJrcuZM8brtg2Dy/qVaNFETvenjIfHVGEwdGbvTvbdrvtD1qBr3adHI4Qd2TcBOfanTE6EW2gGq6wsLlUSCT8H69kpU4aG1vgX8D8h2zJr0ZaG8dYZOLm2isaLy7FzbdsfzgqrYshQLECdgcJod7wM43xLGqlO1sQxi0FehHVaFSCu1FW7TFAnpDM3rlk9G8kU23B1rYD+1/p0KnmQ/qIyXeCDQfHlRfPeA6Ly57ABeJWHMECeL/Jcxhj9eOEWyXObW9XgWqBIpzxFKVSWy+mJD4KoAB3MyD2mBosCYn65j6Q+NWZZoNl/HKnheekGNzXl/gAIeLaYhEzfF87K1E8JZb645XGNsl7jf55zyDlX0r4NM1fyCxRdZ02oM2t74upqqNHMdQNHoEM7UTJk7kYx+M6UWYX6RFcb9ICjRAYX8jg4ptjfiFOTH9XBTcKWopkBf9tBhIaP4e63qY+Nsx6vyZkEen09rxViT+rgZ3X97AtFPslhsJm+8Bto9w9fsToL4Zpm691GdQPe5rjtBD+feSxSIBvRKJZEoRsL84UZKeE9Nd+8PIbAuN9IDJsFDvRcZLFvZBtiAzh2NPGofIXOBYC7RvKwsFH5mFMBXNAJCNwKvDP0giOt4qtvFLnrBRDa1siXDAmTSe1WqWxh+XM8IhH0q8w=
    - PORTAGE_ROOT="$(mktemp --directory)"
    - PORTAGE_VERSION="$(tools/get_latest_portage_version.sh)"

install:
  - tools/setup_portage.sh
  - export PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"
  - export PORTAGE_CONFIGROOT="${PORTAGE_ROOT}" ROOT="${PORTAGE_ROOT}"

before_script:
  - pip install PyYAML
#  - pip install lxml

  - sudo chmod a+rwX /etc/passwd /etc/group /etc /var /var/cache
#  - mkdir -p travis-overlay /etc/portage /var/cache/distfiles /var/db/repos/gentoo
#  - mv !(travis-overlay) travis-overlay/
#  - mv .git travis-overlay/


#  - wget -qO - "https://github.com/gentoo/portage/archive/portage-${PORTAGE_VER}.tar.gz" | tar xz
#  - wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | tar xz -C /var/db/repos/gentoo --strip-components=1

  - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
  - echo "portage::250:portage,travis" >> /etc/group
#  - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
#  - ln -s $TRAVIS_BUILD_DIR/portage-portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/repos.conf
#  - ln -s /var/db/repos/gentoo/profiles/default/linux/amd64/17.0 /etc/portage/make.profile


#  - cd travis-overlay


script:
  - repoman full --include-dev

after_success:
  - bash <(curl --silent https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

#notifications:
#  email:
#    on_failure: change
