#!/usr/bin/env bash

set -e

PORTAGE_UID=250
PORTAGE_GID=250
PORTAGE_HOME="/var/tmp/portage"

mkdir --parents "${PORTAGE_HOME}"

sudo groupadd --gid "${PORTAGE_GID}" portage

sudo useradd --uid "${PORTAGE_UID}" --gid "${PORTAGE_GID}" --home "${PORTAGE_HOME}" --shell /bin/false portage

sudo usermod --append --groups portage "${USER}"
