#!/usr/bin/env bash

set -e

if [ -z "${PORTAGE_ROOT}" ]; then
  echo "PORTAGE_ROOT not set"
  exit 1
fi

if [ -z "${PORTAGE_VERSION}" ]; then
  echo "PORTAGE_VERSION not set"
  exit 1
fi

echo -e "\e[1;33m Used Portage version is: ${PORTAGE_VERSION}"

temporary_directory="$(mktemp --directory)"
portage_extracted_directory=${temporary_directory}/portage-archive
mkdir "${portage_extracted_directory}"
curl --location --silent "https://github.com/gentoo/portage/archive/portage-${PORTAGE_VERSION}.tar.gz" | tar --extract --gzip --directory="${portage_extracted_directory}" --strip-components=1
cd "${portage_extracted_directory}"
./setup.py install -O2 --system-prefix="${PORTAGE_ROOT}/usr" --sysconfdir="${PORTAGE_ROOT}/etc"
cd "${portage_extracted_directory}/repoman"
./setup.py install -O2 --system-prefix="${PORTAGE_ROOT}/usr" --sysconfdir="${PORTAGE_ROOT}/etc"
sudo mkdir --parents /usr/share/repoman/qa_data
sudo cp "${portage_extracted_directory}/repoman/cnf/qa_data/qa_data.yaml" /usr/share/repoman/qa_data/
rm --recursive --force "${temporary_directory}"