#!/usr/bin/env bash

set -e

if [ -z "${PORTAGE_ROOT}" ]; then
  echo "PORTAGE_ROOT not set"
  exit 1
fi

gentoo_tree_dir="${PORTAGE_ROOT}/usr/portage"
mkdir --parents "${gentoo_tree_dir}"
curl --location --silent "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | tar --extract --gzip --directory="${gentoo_tree_dir}" --strip-components=1

portage_conf_dir="${PORTAGE_ROOT}/etc/portage"
mkdir --parents "${portage_conf_dir}/repos.conf"
cat >"${portage_conf_dir}/repos.conf/repos" <<_EOF_
[DEFAULT]
main-repo = gentoo

[gentoo]
location = ${gentoo_tree_dir}

[$(<"${TRAVIS_BUILD_DIR}/profiles/repo_name")]
location = ${TRAVIS_BUILD_DIR}
_EOF_

cat "${portage_conf_dir}/repos.conf/repos"

cat >"${portage_conf_dir}/make.conf" <<_EOF_
PORTAGE_TMPDIR="$(mktemp --directory)"
PKGDIR="$(mktemp --directory)"
DISTDIR="$(mktemp --directory)"
RPMDIR="$(mktemp --directory)"
_EOF_

cat "${portage_conf_dir}/make.conf",

ln --symbolic "${gentoo_tree_dir}/profiles/default/linux/${TRAVIS_CPU_ARCH}/17.1" "${portage_conf_dir}/make.profile"
